USE [Quản lý trung tâm học thêm]

CREATE TABLE MUCTHANHTOAN (
	MaMTT CHAR(6) PRIMARY KEY,
	TiLe FLOAT
)

CREATE TABLE GIAOVIEN (
	MaGV CHAR(6) PRIMARY KEY,
	HoTen NVARCHAR(30),
	SDT CHAR(10),
	NgaySinh DATE,
	DiaChi NVARCHAR(50),
	GioiTinh NVARCHAR(5) CHECK (GioiTinh in (N'Nam', N'Nữ')),
	MaMTT CHAR(6),
	CONSTRAINT FK_GiaoVienMucThanhToan FOREIGN KEY (MaMTT) REFERENCES MUCTHANHTOAN(MaMTT)
)

CREATE TABLE BIENLAITRALUONG (
	MaBL CHAR(6) PRIMARY KEY,
	NgayTra DATE,
	TONGTIEN DECIMAL(19,4),
	MaGV CHAR(6),
	CONSTRAINT FK_BienLaiGiaoVien FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV)
)

CREATE TABLE MONHOC (
	MaMH CHAR(6) PRIMARY KEY,
	TenMH NVARCHAR(20)
)

CREATE TABLE MUCHOCPHI (
	MaMHP CHAR(6) PRIMARY KEY,
	HocPhi1Buoi DECIMAL(19,4)
)

CREATE TABLE LOPHOC (
	MaLH CHAR(6) PRIMARY KEY,
	TenLH NVARCHAR(20),
	MaMH CHAR(6),
	MaGV CHAR(6),
	MaMHP CHAR(6),
	CONSTRAINT FK_LopHocGiaoVien FOREIGN KEY (MaGV) REFERENCES GIAOVIEN(MaGV),
	CONSTRAINT FK_LopHocMonHoc FOREIGN KEY (MaMH) REFERENCES MONHOC(MaMH),
	CONSTRAINT FK_LopHocMucHocPhi FOREIGN KEY (MaMHP) REFERENCES MUCHOCPHI(MaMHP)
)

CREATE TABLE BUOIHOC (
	MaBH CHAR(6) PRIMARY KEY,
	ThoiGian DATETIME,
	MaLH CHAR(6),
	CONSTRAINT FK_BuoiHocLopHoc FOREIGN KEY (MaLH) REFERENCES LOPHOC(MaLH)
)

CREATE TABLE HOCVIEN (
	MaHV CHAR(6) PRIMARY KEY,
	HoTen NVARCHAR(30),
	SDT CHAR(10),
	NgaySinh DATE,
	DiaChi NVARCHAR(50),
	GioiTinh NVARCHAR(5) CHECK (GioiTinh in (N'Nam', N'Nữ'))
)

CREATE TABLE DIEMDANH (
	MaBH CHAR(6),
	MaHV CHAR(6),
	CoTrenLop BIT,
	PRIMARY KEY (MaBH, MaHV),
	CONSTRAINT FK_DiemDanhBuoiHoc FOREIGN KEY (MaBH) REFERENCES BUOIHOC(MaBH),
	CONSTRAINT FK_DiemDanhHocVien FOREIGN KEY (MaHV) REFERENCES HOCVIEN(MaHV)
)

CREATE TABLE BIENLAITHUHOCPHI (
	MaBL CHAR(10) PRIMARY KEY,
	NgayThu DATE,
	TongTien DECIMAL(19,4),
	Thang INT,
	MaHV CHAR(6),
	CONSTRAINT FK_BienLaiHocVien FOREIGN KEY (MaHV) REFERENCES HOCVIEN(MaHV)
)

CREATE TABLE THONGTINNO (
	MaNo CHAR(6) PRIMARY KEY,
	SoThangChuaTra INT,
	MaHV CHAR(6),
	CONSTRAINT FK_NoHocVien FOREIGN KEY (MaHV) REFERENCES HOCVIEN(MaHV)
)

CREATE TABLE HOCVIEN_LOPHOC (
	MaHV CHAR(6),
	MaLH CHAR(6),
	PRIMARY KEY (MaHV, MaLH),
	CONSTRAINT FK_HOCVIEN FOREIGN KEY (MaHV) REFERENCES HOCVIEN(MaHV),
	CONSTRAINT FK_LOPHOC FOREIGN KEY (MaLH) REFERENCES LOPHOC(MaLH)
)

--DELETE BIENLAITHUHOCPHI
--DELETE BIENLAITRALUONG
--DELETE MUCTHANHTOAN
--DELETE DIEMDANH
--DELETE HOCVIEN
--DELETE BUOIHOC
--DELETE LOPHOC
--DELETE GIAOVIEN
--DELETE MUCHOCPHI
--DELETE MONHOC

--DROP TABLE BIENLAITHUHOCPHI
--DROP TABLE THONGTINNO
--DROP TABLE BIENLAITRALUONG
--DROP TABLE MUCTHANHTOAN
--DROP TABLE DIEMDANH
--DROP TABLE HOCVIEN
--DROP TABLE BUOIHOC
--DROP TABLE LOPHOC
--DROP TABLE GIAOVIEN
--DROP TABLE MUCHOCPHI
--DROP TABLE MONHOC